import {
  Row,
  Col,
  Container,
  List
} from 'reactstrap';
import DisplayCard from '../display/DisplayCard';
import CBOchart1 from '../assets/CBO_wealth_chart_1.png';
import CBOchart2 from '../assets/wealth_increase_distribution.png'
import wageGroup from '../assets/EPI_wage_group.png';
import productivity from '../assets/EPI_productivity.png';
import "./Mission.css";
import oligarchy from '../assets/definition_oligarchy.png';
import plutocracy from '../assets/definition_plutocracy.png';

//list benefits of better pay/less hours
// -mental health, happiness, 
const Mission = () => {

  return (
    <Container className="full-width">
    <Row>
      <Col className='text-center lrmargin10 mt-3' >
        <h1>Our Mission is to Improve the Lives of Workers</h1>
        <h2>We will break the Barriers of Division Created by Politicians and the Media, Unite Workers and Demand Change</h2>
      </Col>
    </Row>

    <Row className='lrmargin3'>
      <Col className='col-12 bgLornge lrmargin3 my-3 col-md-5' >
        <h3 className='text-center'>Our Goals</h3>
        <List>
          <li>Increase wages of the lower and middle classes</li>
          <li>Reduce number of hours worked per week</li>
          <li>Create a workers bill of rights</li>
          <li>Remove the ability for corporations and the wealthy to own politicians</li>
          <li>Decrease corruption - increase transparency</li>
          <li>Overhaul the healthcare system so workers can afford healthcare</li>
        </List>
      </Col>
      <Col className='col-12 bgLornge lrmargin3 my-3 col-md-5'>
        <h3 className='text-center'>Benefits of achieving our goals</h3>
        <List>
          <li>Strengthened economy</li>
          <li>Healthier society</li>
          <li>Reduction in crime</li>
          <li>Nationwide improved happiness/decreased depression</li>
          <li>Reduced wealth/income inequality</li>
          <li>Decreased political corruption</li>
          <li>More jobs/reduced unemployment</li>
          <li>Reduce advantage large corporations have over small businesses</li>
        </List>
      </Col>
    </Row>

    <Row>
      <Col className='text-center lrmargin10 mt-3' >
        <h3>Our purchasing power decreases each year and they tell us to budget better</h3>
        <h4>Their bank accounts fatten each year and it's time we tell them to buy fewer yachts and private jets</h4>
      </Col>
    </Row>
    
    <Row className='my-3 lrmargin10 text-center'>
      <Col className='col-lg-6'>
        <img src={oligarchy} alt="definition of oligarchy" className='definition'/>
      </Col>
      <Col className='col-lg-6'>
        <img src={plutocracy} alt="definition of plutocracy" className='definition'/>
      </Col>
    </Row>

    <Row className='bggrn lrmargin10 text-center'>
      <Col>
        <h3>The terms oligarchy and plutocracy can both be used to accurately describe the USA</h3>
        <h3>If we truly want a government "of the people, by the people, for the people" we must remove money's influence on politics</h3> 

      </Col>
    </Row>

    {/* First Row of charts */}
    <Row className='my-3'>
      <Col className='col-12 col-lg-6' style={{color: 'black'}}>
    <DisplayCard
      title="Worker compensation no longer reflects productivity improvements"
      subtitle="Average worker's compensation increased with productivity until early 1980s"
      image={productivity}
      text="Workers' compensation has stagnated for the past 40 years and productivity increases have gone to the top"
      alt="Productivity Pay Gap"
      link="https://www.epi.org/productivity-pay-gap/"
      linksource="Economic Policy Institute"
      linkname="The Productivity Pay Gap"
      />
      </Col>
      <Col className='col-12 col-lg-6' style={{color: 'black'}}>
    <DisplayCard
      title="Wage increases have been concentrated in the top 1% of earners and the top 0.1% stealing the profits generated by workers"
      subtitle="Why are not all employees wages tied to corporate profits?"
      image={wageGroup}
      text="The increase of income inequality coincides with a reduction in quality of life for Americans. Now is the time to take the power back for workers"
      link="https://www.epi.org/data/#?subject=wagegroup"
      linksource="Economic Policy Institute"
      linkname="Annual wages by wage group"
      />
      </Col>
      </Row>

      {/* Second Row of charts */}
      <Row className='mb-3' >
      <Col className='col-12 col-lg-6' style={{color: 'black'}}>
    <DisplayCard
      title="Ever increasing worker exploitation has devastated the bottom 50%"
      subtitle="Since 1989 the wealth of the top 10% has almost quadrupled and is around 40 times that of the bottom 50%"
      image={CBOchart1}
      text="This trend will continue unless we fight for fair compensation"
      alt="Total Family Wealth by Wealth Group"
      link="https://www.cbo.gov/publication/57598"
      linksource="Congressional Budget Office"
      linkname="Trends in the Distribution of Family Wealth, 1989 to 2019"
      />
      </Col>
      <Col className='col-12 col-lg-6' style={{color: 'black'}}>
    <DisplayCard
      title="The top 1% holds 34% of the wealth in the USA, a 7% increase since 1989"
      subtitle="The bottom 50% hold 2% of wealth, half as much as in 1989"
      image={CBOchart2}
      text="For decades, the wealthy have been paying politicians to erode our rights and transfer wealth to the top. We must stand up for ourselves"
      alt="Total Family Wealth by Wealth Group"
      link="https://www.cbo.gov/publication/57598"
      linksource="Congressional Budget Office"
      linkname="Trends in the Distribution of Family Wealth, 1989 to 2019"
      />
      </Col>
      </Row>


      <Row>
        <Col>
        sdf
        </Col>
      </Row>
      </Container>



          // {/* Card 1 */}
        //   <Row className='text-center lrmargin'>
        //   <Col>
        //     <Card>
        //       <img
        //       alt="Total Family Wealth by Wealth Group"
        //       src={CBOchart1}
        //       />
        //       <CardBody>
        //         <CardTitle tag="h5">
        //           Ever increasing worker exploitation has devastated the bottom 50%
        //         </CardTitle>
        //         <CardSubtitle
        //         className='mb-2 text-muted'
        //         tag='h6'
        //         >
        //           Since 1989 the wealth of the top 10% has almost quadrupled and is around 40 times that of the bottom 50%
        //         </CardSubtitle>
        //         <CardText>
        //         This trend will continue unless we fight for fair compensation
        //         </CardText>
        //         <CardLink href="https://www.cbo.gov/publication/57598">
        //           Congressional Budget Office <em>Trends in the Distribution of Family Wealth, 1989 to 2019</em>
        //         </CardLink>
        //       </CardBody>
        //     </Card>
        //   </Col>
        // </Row>

  );
}

export default Mission;